# Generated by Django 2.1.5 on 2019-01-16 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.IntegerField(choices=[(1, 'Приход'), (2, 'Расход')], default=2)),
                ('quantity', models.FloatField()),
                ('unit', models.IntegerField(choices=[(1, 'Килограмм'), (2, 'Штуки'), (3, 'Литр'), (4, 'Метр')])),
                ('price', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('comment', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'Нормальный'), (2, 'Удалено')], default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
