# Generated by Django 2.1.5 on 2019-01-25 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 1, 25, 11, 40, 19, 480131)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 25)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='unit',
            field=models.IntegerField(choices=[(1, 'Килограмм'), (2, 'Штука'), (3, 'Литр'), (4, 'Метр')]),
        ),
    ]
